[[constraint]]
  name = "github.com/circonus-labs/circonus-gometrics"
  version = "2.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/snappy"

[[constraint]]
  name = "github.com/google/gopacket"
  version = "1.1.14"

[prune]
  go-tests = true
  unused-packages = true
